name: golang-ci

on:
  release:
    types: [created]

jobs:
  build:
    name: release go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
        goarch:
          - amd64
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build gorkscrew binary
        uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.16
