# Name of the workflow
name: Add Version Shell Script

on:
  workflow_dispatch:

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Shell Version"
    runs-on: "ubuntu-latest"
    environment: "prod"

    steps:
      - name: Check out code into the go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Latest Release
        run: echo 'version ${{ steps.previoustag.outputs.tag }}'

      - name: Add version install.sh
        run: sed -i 's/v[0-9].[0-9].[0-9]/${{ steps.previoustag.outputs.tag }}/i' install.sh

      - name: Commit files # transfer the new html files back into the repository
        run: |
          git config --local user.name  ${{ github.actor }}
          git add ./docs
          git commit -m "added version ${{ steps.previoustag.outputs.tag }} in install.sh"

      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
